//! JSON-RPC framing, protocol versions and MCP message types.

mod json_rpc;
mod types;
mod versions;

pub use json_rpc::INTERNAL_ERROR;
pub use json_rpc::INVALID_PARAMS;
pub use json_rpc::INVALID_REQUEST;
pub use json_rpc::JSONRPC_VERSION;
pub use json_rpc::JsonRpcError;
pub use json_rpc::JsonRpcErrorObject;
pub use json_rpc::JsonRpcMessage;
pub use json_rpc::JsonRpcNotification;
pub use json_rpc::JsonRpcRequest;
pub use json_rpc::JsonRpcResponse;
pub use json_rpc::METHOD_NOT_FOUND;
pub use json_rpc::PARSE_ERROR;
pub use json_rpc::RequestId;
pub use types::CallToolResult;
pub use types::ClientCapabilities;
pub use types::CompleteParams;
pub use types::CompleteResult;
pub use types::Completion;
pub use types::CompletionArgument;
pub use types::CompletionContext;
pub use types::CompletionReference;
pub use types::Content;
pub use types::DiscoverResult;
pub use types::ElicitAction;
pub use types::ElicitResult;
pub use types::ElicitationCapability;
pub use types::ElicitationRequest;
pub use types::GetPromptResult;
pub use types::Implementation;
pub use types::InitializeResult;
pub use types::ListCapability;
pub use types::ListPromptsResult;
pub use types::ListResourceTemplatesResult;
pub use types::ListResourcesResult;
pub use types::ListToolsResult;
pub use types::McpTool;
pub use types::Prompt;
pub use types::PromptArgument;
pub use types::PromptMessage;
pub use types::ReadResourceResult;
pub use types::Resource;
pub use types::ResourceContents;
pub use types::ResourceTemplate;
pub use types::ServerCapabilities;
pub use types::ToolAnnotations;
pub use versions::LATEST_LEGACY_PROTOCOL_VERSION;
pub use versions::LATEST_PROTOCOL_VERSION;
pub use versions::META_CLIENT_CAPABILITIES;
pub use versions::META_CLIENT_INFO;
pub use versions::META_PROTOCOL_VERSION;
pub use versions::META_SERVER_INFO;
pub use versions::MODERN_PROTOCOL_ERROR_CODES;
pub use versions::ProtocolEra;
pub use versions::SUPPORTED_PROTOCOL_VERSIONS;
pub use versions::is_supported_version;
